dataset:
  type: /app/examples/weather/corrdiff/datasets/custom_list_2.py::CustomDataset
  data_path:
  - /mnt/storage/younes.abid/physicsnemo/data/custom_data_2/ERA5_WRF_combined_concatenated_432/2020-12-31_2021-06-27_150.nc
  - /mnt/storage/younes.abid/physicsnemo/data/custom_data_2/ERA5_WRF_combined_concatenated_432/2021-06-28_2021-12-22_150.nc
  - /mnt/storage/younes.abid/physicsnemo/data/custom_data_2/ERA5_WRF_combined_concatenated_432/2021-12-23_2022-06-04_150.nc
  stats_path: /mnt/storage/younes.abid/physicsnemo/data/custom_data_2/stats_432/stat.json
  input_variables:
  - t_850
  - t_500
  - z_850
  - z_500
  - u_850
  - u_500
  - v_850
  - v_500
  - u10
  - v10
  - t2m
  - d2m
  - skt
  - sp
  - tcwv
  - tp
  output_variables:
  - U10
  - V10
  invariant_variables: []
model:
  name: diffusion
  hr_mean_conditioning: true
  model_args:
    gridtype: sinusoidal
    N_grid_channels: 4
    embedding_type: zero
    model_channels: 128
    channel_mult:
    - 1
    - 2
    - 2
    - 2
    - 2
    attn_resolutions:
    - 28
training:
  hp:
    training_duration: 295000
    total_batch_size: 16
    batch_size_per_gpu: 2
    lr: 5.0e-05
    grad_clip_threshold: null
    lr_decay: 0.9
    lr_rampup: 5000
    lr_decay_rate: 50000.0
  perf:
    fp_optimizations: fp32
    dataloader_workers: 32
    songunet_checkpoint_level: 0
    use_gpu: true
    num_gpus: -1
  io:
    regression_checkpoint_path: /app/checkpoints_regression/UNet.0.535008.mdlus
    print_progress_freq: 500
    metric_log_freq: 1
    image_log_freq: 4000
    save_checkpoint_freq: 5000
    save_n_recent_checkpoints: 10
    validation_freq: 500
    validation_steps: 100
    load_optimizer: false
    grad_log_freq: 400
validation:
  data_path:
  - /mnt/storage/younes.abid/physicsnemo/data/custom_data_2/ERA5_WRF_combined_concatenated_432/2024-04-30_2024-05-30_21.nc
  stats_path: /mnt/storage/younes.abid/physicsnemo/data/custom_data_2/stats_432/stat.json
  input_variables:
  - t_850
  - t_500
  - z_850
  - z_500
  - u_850
  - u_500
  - v_850
  - v_500
  - u10
  - v10
  - t2m
  - d2m
  - skt
  - sp
  - tcwv
  - tp
  output_variables:
  - U10
  - V10
  invariant_variables: []
tensorboard:
  log_dir: /app/tensorboard/diffusion
wandb:
  mode: offline
  results_dir: /app/wandb/diffusion
  watch_model: false